### ISSUE TITLE
rc.init: mount /proc

### ISSUE THREAD

**Issue by ghost** [michaelforney/oasis-etc#1]
`mount /proc` [diff](
https://github.com/oasislinux/etc/commit/907c7b50bf1ad4ab0afc50742c91cdd56e58762a#diff-8f5164e2fad8cb0c00a2c891a8b747aac2ebe6bb4411a3adb856a01bda97a2da) vs oasis musl version: 1.2.2 and new [realpath](https://git.musl-libc.org/cgit/musl/commit/?id=29ff7599a448232f2527841c2362643d246cee36
) in musl libc.

**Comment by michaelforney** [comment]
Looks like `realpath` is not the only thing in mount(8) that needs /proc. It also needs /proc/mounts to check which filesystems are already mounted.

So, looks like the initial `mount -t proc none /proc` will have to stay.
